### ISSUE TITLE
Optimize Structuremap usage (performance)

### ISSUE THREAD

**Issue by 304NotModified** [roadkillwiki/roadkill#32]
As proposed at https://github.com/roadkillwiki/roadkill/issues/17

**Comment by 304NotModified** [comment]
@yetanotherchris 

this is fixed by https://github.com/roadkillwiki/roadkill/pull/37?

**Comment by yetanotherchris** [comment]
Not fixed quite yet, there's a branch that fixes an IoC problem with the IUnitOfWork
